# Generated by Django 3.2.8 on 2021-12-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_auto_20211230_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
